# Generated by Django 2.2 on 2021-11-11 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comunitaria', '0069_documentfile'),
        ('energy_metering', '0009_auto_20210831_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('energy_amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('watt_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='comunitaria.Community')),
            ],
        ),
    ]
